name: Build and Push Jupyter Images

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: datascience
            context: datascience
          - name: astronomy
            context: astronomy
          - name: solarsystem
            context: solarsystem

    env:
      DOCKERHUB_ORG: linea

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set build metadata
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "PYTHON_TAG=python-3.13" >> $GITHUB_ENV
          echo "IMAGE_NAME=${DOCKERHUB_ORG}/jupyter-${{ matrix.image.name }}" >> $GITHUB_ENV

      # Setup Buildx (enables cache + parallel builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Pull Request
      # --------------------------------------------------------------------
      # builds should only build the image without pushing to Docker Hub
      - name: Build (PR only - no push)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.context }}/Dockerfile
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DATE }}
            ${{ env.IMAGE_NAME }}:${{ env.PYTHON_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Push or Manual
      # --------------------------------------------------------------------
      # builds and push the image to Docker Hub,
      # but only on main branch or manual trigger (not on PRs)
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (main & manual)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.context }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DATE }}
            ${{ env.IMAGE_NAME }}:${{ env.PYTHON_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pushed tags
        if: github.event_name != 'pull_request'
        run: |
          echo "-----------------------------"
          echo "Image Context: ${{ matrix.image.context }}"
          echo "Image Name: $IMAGE_NAME"
          echo "DATE tag  : $IMAGE_NAME:$DATE"
          echo "PYTHON tag: $IMAGE_NAME:$PYTHON_TAG"
          echo "SHA tag   : $IMAGE_NAME:$SHORT_SHA"
          echo "LATEST tag: $IMAGE_NAME:latest"
          echo "-----------------------------"
